extends Node

# Auto-generated by scripts/editor/audio_enums_generator.gd
# DO NOT edit this file as any changes may be overwritten

class SFX:
	const BLOCK = preload("res://audio/sfx/block.wav")
	const COLLECT = preload("res://audio/sfx/collect.wav")
	const DANGER = preload("res://audio/sfx/danger.wav")
	const ENEMY_SHOOT = preload("res://audio/sfx/enemy_shoot.wav")
	const HIT = preload("res://audio/sfx/hit.wav")
	const LOSE = preload("res://audio/sfx/lose.wav")
	const PERFECT = preload("res://audio/sfx/perfect.wav")
	const PLAYER_SHOOT = preload("res://audio/sfx/player_shoot.wav")
	const PLAYER_SHOOT_SPECIAL = preload("res://audio/sfx/player_shoot_special.wav")
	const PLAYER_SHOOT_VAMPIRE = preload("res://audio/sfx/player_shoot_vampire.wav")
	const SELECT = preload("res://audio/sfx/select.wav")
	const SELECT_ALT = preload("res://audio/sfx/select_alt.wav")
	const TURN_OFF = preload("res://audio/sfx/turn_off.wav")
	const TURN_ON = preload("res://audio/sfx/turn_on.wav")
