extends Node

# Auto-generated by scripts/editor/audio_enums_generator.gd
# DO NOT edit this file as any changes may be overwritten

class CUTSCENE:
	const QUAKE = preload("res://audio/cutscene/quake.wav")
class MUSIC:
	const BATTLE = preload("res://audio/music/battle.wav")
	const BOSS = preload("res://audio/music/boss.wav")
	const TOWN = preload("res://audio/music/town.wav")
class SFX:
	const BLOCK = preload("res://audio/sfx/block.wav")
	const BOSS_DEATH = preload("res://audio/sfx/boss_death.wav")
	const COLLECT = preload("res://audio/sfx/collect.wav")
	const DANGER = preload("res://audio/sfx/danger.wav")
	const ENEMY_SHOOT = preload("res://audio/sfx/enemy_shoot.wav")
	const HISS = preload("res://audio/sfx/hiss.mp3")
	const HISS_SOFT = preload("res://audio/sfx/hiss_soft.mp3")
	const HIT = preload("res://audio/sfx/hit.wav")
	const LOSE = preload("res://audio/sfx/lose.wav")
	const PERFECT = preload("res://audio/sfx/perfect.wav")
	const PLAYER_SHOOT = preload("res://audio/sfx/player_shoot.wav")
	const PLAYER_SHOOT_SPECIAL = preload("res://audio/sfx/player_shoot_special.wav")
	const PLAYER_SHOOT_VAMPIRE = preload("res://audio/sfx/player_shoot_vampire.wav")
	const SELECT = preload("res://audio/sfx/select.wav")
	const SELECT_ALT = preload("res://audio/sfx/select_alt.wav")
	const TURN_OFF = preload("res://audio/sfx/turn_off.wav")
	const TURN_ON = preload("res://audio/sfx/turn_on.wav")
