@tool
extends EditorScript

const AUDIO_DIR_PATH: String = "res://audio"
const OUTPUT_FILE_PATH: String = "res://scripts/global/audio_consts.gd"
const VALID_EXTENSIONS: Array = ["wav", "ogg", "mp3"]

# EDITOR SCRIPT: used to write consts with audio data to a Singleton audio_consts.gd script
# ctrl + shift + x to update
func _run() -> void:
	var audio_dir := DirAccess.open(AUDIO_DIR_PATH)
	var code: String = "extends Node\n\n# Auto-generated by scripts/editor/audio_enums_generator.gd\n# DO NOT edit this file as any changes may be overwritten\n\n"
	
	if not audio_dir:
		push_error("Couldn't access 'audio' folder")
		return
	
	var sub_dirs: PackedStringArray = audio_dir.get_directories()
	
	for sub_name in sub_dirs:
		var dir := DirAccess.open(AUDIO_DIR_PATH.path_join(sub_name))
		
		code += "class " + sub_name.to_snake_case().to_upper() + ":\n"
		
		for file_name in dir.get_files():
			if file_name.get_extension() not in VALID_EXTENSIONS:
				continue
			
			code += "\tconst " + file_name.get_basename().to_snake_case().to_upper() + " = " + "preload(\"" + AUDIO_DIR_PATH.path_join(sub_name).path_join(file_name) + "\")\n"
	
	var output_file := FileAccess.open(OUTPUT_FILE_PATH, FileAccess.WRITE)
	
	output_file.store_string(code)
	output_file.close()
	
	EditorInterface.get_resource_filesystem().scan()
	
	print("New audio enum script has been saved to '" + OUTPUT_FILE_PATH + "'")
